version: "3.1"
services:
  tbbo:
    build: .
    container_name: tbbo-app
    depends_on:
      - db
    volumes:
      - ${PWD}/:/app
      - $TBBO_CONFIG:/TheBestBookOn.com/bestbook/configs/settings.cfg
    ports:
      - 31337:31337
  db:
    container_name: tbbo-db
    image: postgres:14.1
    environment:
      - POSTGRES_USER=bestbook
      - POSTGRES_PASSWORD=$PSQL_PASSWD
      - POSTGRES_DB=bestbooks
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
